/*
 * WordsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.rapidapi.p.wordsapiv1.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PronunciationDetails type.
 */
public class PronunciationDetails {
    private String all;
    private String noun;
    private String verb;

    /**
     * Default constructor.
     */
    public PronunciationDetails() {
    }

    /**
     * Initialization constructor.
     * @param  all  String value for all.
     * @param  noun  String value for noun.
     * @param  verb  String value for verb.
     */
    public PronunciationDetails(
            String all,
            String noun,
            String verb) {
        this.all = all;
        this.noun = noun;
        this.verb = verb;
    }

    /**
     * Getter for All.
     * The pronunciation of the word.
     * @return Returns the String
     */
    @JsonGetter("all")
    public String getAll() {
        return all;
    }

    /**
     * Setter for All.
     * The pronunciation of the word.
     * @param all Value for String
     */
    @JsonSetter("all")
    public void setAll(String all) {
        this.all = all;
    }

    /**
     * Getter for Noun.
     * The noun pronunciation of the word.
     * @return Returns the String
     */
    @JsonGetter("noun")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNoun() {
        return noun;
    }

    /**
     * Setter for Noun.
     * The noun pronunciation of the word.
     * @param noun Value for String
     */
    @JsonSetter("noun")
    public void setNoun(String noun) {
        this.noun = noun;
    }

    /**
     * Getter for Verb.
     * The verb pronunciation of the word.
     * @return Returns the String
     */
    @JsonGetter("verb")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getVerb() {
        return verb;
    }

    /**
     * Setter for Verb.
     * The verb pronunciation of the word.
     * @param verb Value for String
     */
    @JsonSetter("verb")
    public void setVerb(String verb) {
        this.verb = verb;
    }

    /**
     * Converts this PronunciationDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PronunciationDetails [" + "all=" + all + ", noun=" + noun + ", verb=" + verb + "]";
    }

    /**
     * Builds a new {@link PronunciationDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PronunciationDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(all)
                .noun(getNoun())
                .verb(getVerb());
        return builder;
    }

    /**
     * Class to build instances of {@link PronunciationDetails}.
     */
    public static class Builder {
        private String all;
        private String noun;
        private String verb;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  all  String value for all.
         */
        public Builder(String all) {
            this.all = all;
        }

        /**
         * Setter for all.
         * @param  all  String value for all.
         * @return Builder
         */
        public Builder all(String all) {
            this.all = all;
            return this;
        }

        /**
         * Setter for noun.
         * @param  noun  String value for noun.
         * @return Builder
         */
        public Builder noun(String noun) {
            this.noun = noun;
            return this;
        }

        /**
         * Setter for verb.
         * @param  verb  String value for verb.
         * @return Builder
         */
        public Builder verb(String verb) {
            this.verb = verb;
            return this;
        }

        /**
         * Builds a new {@link PronunciationDetails} object using the set fields.
         * @return {@link PronunciationDetails}
         */
        public PronunciationDetails build() {
            return new PronunciationDetails(all, noun, verb);
        }
    }
}
