/*
 * WordsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.rapidapi.p.wordsapiv1.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PronunciationResponse type.
 */
public class PronunciationResponse {
    private String word;
    private PronunciationDetails pronunciation;

    /**
     * Default constructor.
     */
    public PronunciationResponse() {
    }

    /**
     * Initialization constructor.
     * @param  word  String value for word.
     * @param  pronunciation  PronunciationDetails value for pronunciation.
     */
    public PronunciationResponse(
            String word,
            PronunciationDetails pronunciation) {
        this.word = word;
        this.pronunciation = pronunciation;
    }

    /**
     * Getter for Word.
     * The word that is searched.
     * @return Returns the String
     */
    @JsonGetter("word")
    public String getWord() {
        return word;
    }

    /**
     * Setter for Word.
     * The word that is searched.
     * @param word Value for String
     */
    @JsonSetter("word")
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * Getter for Pronunciation.
     * This model contains pronunciation details of a specific word.
     * @return Returns the PronunciationDetails
     */
    @JsonGetter("pronunciation")
    public PronunciationDetails getPronunciation() {
        return pronunciation;
    }

    /**
     * Setter for Pronunciation.
     * This model contains pronunciation details of a specific word.
     * @param pronunciation Value for PronunciationDetails
     */
    @JsonSetter("pronunciation")
    public void setPronunciation(PronunciationDetails pronunciation) {
        this.pronunciation = pronunciation;
    }

    /**
     * Converts this PronunciationResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PronunciationResponse [" + "word=" + word + ", pronunciation=" + pronunciation
                + "]";
    }

    /**
     * Builds a new {@link PronunciationResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PronunciationResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(word, pronunciation);
        return builder;
    }

    /**
     * Class to build instances of {@link PronunciationResponse}.
     */
    public static class Builder {
        private String word;
        private PronunciationDetails pronunciation;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  word  String value for word.
         * @param  pronunciation  PronunciationDetails value for pronunciation.
         */
        public Builder(String word, PronunciationDetails pronunciation) {
            this.word = word;
            this.pronunciation = pronunciation;
        }

        /**
         * Setter for word.
         * @param  word  String value for word.
         * @return Builder
         */
        public Builder word(String word) {
            this.word = word;
            return this;
        }

        /**
         * Setter for pronunciation.
         * @param  pronunciation  PronunciationDetails value for pronunciation.
         * @return Builder
         */
        public Builder pronunciation(PronunciationDetails pronunciation) {
            this.pronunciation = pronunciation;
            return this;
        }

        /**
         * Builds a new {@link PronunciationResponse} object using the set fields.
         * @return {@link PronunciationResponse}
         */
        public PronunciationResponse build() {
            return new PronunciationResponse(word, pronunciation);
        }
    }
}
