/*
 * WordsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.rapidapi.p.wordsapiv1.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SyllableDetails type.
 */
public class SyllableDetails {
    private Integer count;
    private List<String> list;

    /**
     * Default constructor.
     */
    public SyllableDetails() {
    }

    /**
     * Initialization constructor.
     * @param  count  Integer value for count.
     * @param  list  List of String value for list.
     */
    public SyllableDetails(
            Integer count,
            List<String> list) {
        this.count = count;
        this.list = list;
    }

    /**
     * Getter for Count.
     * The count of syllables.
     * @return Returns the Integer
     */
    @JsonGetter("count")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCount() {
        return count;
    }

    /**
     * Setter for Count.
     * The count of syllables.
     * @param count Value for Integer
     */
    @JsonSetter("count")
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * Getter for List.
     * The list of syllables.
     * @return Returns the List of String
     */
    @JsonGetter("list")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getList() {
        return list;
    }

    /**
     * Setter for List.
     * The list of syllables.
     * @param list Value for List of String
     */
    @JsonSetter("list")
    public void setList(List<String> list) {
        this.list = list;
    }

    /**
     * Converts this SyllableDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SyllableDetails [" + "count=" + count + ", list=" + list + "]";
    }

    /**
     * Builds a new {@link SyllableDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SyllableDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .count(getCount())
                .list(getList());
        return builder;
    }

    /**
     * Class to build instances of {@link SyllableDetails}.
     */
    public static class Builder {
        private Integer count;
        private List<String> list;



        /**
         * Setter for count.
         * @param  count  Integer value for count.
         * @return Builder
         */
        public Builder count(Integer count) {
            this.count = count;
            return this;
        }

        /**
         * Setter for list.
         * @param  list  List of String value for list.
         * @return Builder
         */
        public Builder list(List<String> list) {
            this.list = list;
            return this;
        }

        /**
         * Builds a new {@link SyllableDetails} object using the set fields.
         * @return {@link SyllableDetails}
         */
        public SyllableDetails build() {
            return new SyllableDetails(count, list);
        }
    }
}
