/*
 * WordsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.rapidapi.p.wordsapiv1.authentication;

import com.rapidapi.p.wordsapiv1.CustomHeaderAuthenticationCredentials;
import io.apimatic.core.authentication.HeaderAuth;
import java.util.HashMap;

public class CustomHeaderAuthenticationManager extends HeaderAuth implements CustomHeaderAuthenticationCredentials {

    /**
     * Private instance of the auth model containing the auth credentials.
     */
    private CustomHeaderAuthenticationModel authModel;

    /**
     * Constructor that sets custom header parameters.
     */
    public CustomHeaderAuthenticationManager(CustomHeaderAuthenticationModel authModel) {

        super(new HashMap<String,String>() {
            private static final long serialVersionUID = 1L;
            {
                put("X-RapidAPI-Key", authModel.getXRapidAPIKey());
            }
        });

        this.authModel = authModel;
    }

    /**
     * String value for xRapidAPIKey.
     * @return xRapidAPIKey
     */
    public String getXRapidAPIKey() {
        return authModel.getXRapidAPIKey();
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param xRapidAPIKey String value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String xRapidAPIKey) {
        return xRapidAPIKey.equals(getXRapidAPIKey());
    }

    /**
     * Converts this CustomHeaderAuthenticationManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CustomHeaderAuthenticationManager [" + "xRapidAPIKey=" + getXRapidAPIKey() + "]";
    }
    /**
    * Returns the error message if the auth credentials are not valid.
    * @return the auth specific error message.
    */
    @Override
    public String getErrorMessage() {
        String errorMessage = super.getErrorMessage();
        if (errorMessage == null) {
            return null;
        }

        return "CustomHeaderAuthentication - " + errorMessage;
     }

}
