/*
 * WordsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.rapidapi.p.wordsapiv1.authentication;

/**
 * A data class for Custom Header Signature credentials.
 */
public class CustomHeaderAuthenticationModel {
    private String xRapidAPIKey;

    /**
     * A Constructor for CustomHeaderAuthenticationModel.
     */
    private CustomHeaderAuthenticationModel(String xRapidAPIKey) {
        this.xRapidAPIKey = xRapidAPIKey;
    }

    /**
     * Getter for xRapidAPIKey.
     * @return xRapidAPIKey The value of X-RapidAPI-Key.
     */
    public String getXRapidAPIKey() {
        return this.xRapidAPIKey;
    }

    /**
     * Builds a new {@link CustomHeaderAuthenticationModel.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link CustomHeaderAuthenticationModel.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getXRapidAPIKey());
    }

    /**
     * A Builder class for Custom Header Signature credentials.
     */
    public static class Builder {
        private String xRapidAPIKey;

        /**
         * The constructor with required auth credentials.
         * @param xRapidAPIKey The value of XRapidAPIKey.
         */
        public Builder(String xRapidAPIKey) {
            if (xRapidAPIKey == null) {
                throw new NullPointerException("XRapidAPIKey cannot be null.");
            }

            this.xRapidAPIKey = xRapidAPIKey;
        }

        /**
         * Setter for xRapidAPIKey.
         * @param xRapidAPIKey The value of X-RapidAPI-Key.
         * @return Builder The current instance of Builder.
         */
        public Builder xRapidAPIKey(String xRapidAPIKey) {
            if (xRapidAPIKey == null) {
                throw new NullPointerException("XRapidAPIKey cannot be null.");
            }

            this.xRapidAPIKey = xRapidAPIKey;
            return this;
        }

        /**
         * Builds the instance of CustomHeaderAuthenticationModel using the provided credentials.
         * @return The instance of CustomHeaderAuthenticationModel.
         */
        public CustomHeaderAuthenticationModel build() {
            return new CustomHeaderAuthenticationModel(xRapidAPIKey);
        }
    }
}